const emojiData = [
  // ====================
  // 笑脸和情感类
  // ====================
  
  // 笑脸和情感/笑脸
  {
    emoji: "😊",
    name: "呵呵",
    category: "笑脸和情感/笑脸",
    description: "slightly smiling face",
    shortcut: "Alt+1",
  },
  {
    emoji: "😀",
    name: "嘿嘿",
    category: "笑脸和情感/笑脸",
    description: "grinning face",
    shortcut: "Alt+4",
  },
  {
    emoji: "😃",
    name: "哈哈",
    category: "笑脸和情感/笑脸",
    description: "grinning face with big eyes",
    shortcut: "Alt+5",
  },
  {
    emoji: "😅",
    name: "苦笑",
    category: "笑脸和情感/笑脸",
    description: "grinning face with sweat",
    shortcut: "Alt+7",
  },
  {
    emoji: "🤣",
    name: "笑得满地打滚",
    category: "笑脸和情感/笑脸",
    description: "rolling on the floor laughing",
    shortcut: "Alt+0",
  },
  {
    emoji: "😂",
    name: "笑哭",
    category: "笑脸和情感/笑脸",
    description: "face with tears of joy",
    shortcut: null,
  },
  {
    emoji: "😭",
    name: "大哭",
    category: "笑脸和情感/笑脸",
    description: "loudly crying face",
    shortcut: null,
  },
  {
    emoji: "😘",
    name: "飞吻",
    category: "笑脸和情感/笑脸",
    description: "face blowing a kiss",
    shortcut: null,
  },
  {
    emoji: "🥰",
    name: "面带微笑的脸",
    category: "笑脸和情感/笑脸",
    description: "smiling face with hearts",
    shortcut: null,
  },
  {
    emoji: "😉",
    name: "眨眼",
    category: "笑脸和情感/笑脸",
    description: "winking face",
    shortcut: null,
  },
  {
    emoji: "🙄",
    name: "白眼",
    category: "笑脸和情感/笑脸",
    description: "face with rolling eyes",
    shortcut: null,
  },
  {
    emoji: "😒",
    name: "不爽",
    category: "笑脸和情感/笑脸",
    description: "unamused face",
    shortcut: null,
  },
  {
    emoji: "🤔",
    name: "思考",
    category: "笑脸和情感/笑脸",
    description: "thinking face",
    shortcut: null,
  },
  {
    emoji: "🤗",
    name: "抱抱",
    category: "笑脸和情感/笑脸",
    description: "hugging face",
    shortcut: null,
  },
  {
    emoji: "🤫",
    name: "嘘",
    category: "笑脸和情感/笑脸",
    description: "shushing face",
    shortcut: null,
  },
  {
    emoji: "🤐",
    name: "拉链嘴",
    category: "笑脸和情感/笑脸",
    description: "zipper-mouth face",
    shortcut: null,
  },
  {
    emoji: "😴",
    name: "睡觉",
    category: "笑脸和情感/笑脸",
    description: "sleeping face",
    shortcut: null,
  },
  {
    emoji: "😷",
    name: "口罩脸",
    category: "笑脸和情感/笑脸",
    description: "face with medical mask",
    shortcut: null,
  },
  {
    emoji: "🤒",
    name: "发烧",
    category: "笑脸和情感/笑脸",
    description: "face with thermometer",
    shortcut: null,
  },
  {
    emoji: "🤢",
    name: "恶心",
    category: "笑脸和情感/笑脸",
    description: "nauseated face",
    shortcut: null,
  },
  {
    emoji: "😱",
    name: "尖叫",
    category: "笑脸和情感/笑脸",
    description: "face screaming in fear",
    shortcut: null,
  },
  {
    emoji: "😇",
    name: "天使",
    category: "笑脸和情感/笑脸",
    description: "smiling face with halo",
    shortcut: null,
  },
  {
    emoji: "🤯",
    name: "头爆炸",
    category: "笑脸和情感/笑脸",
    description: "exploding head",
    shortcut: null,
  },
  {
    emoji: "😎",
    name: "墨镜笑脸",
    category: "笑脸和情感/笑脸",
    description: "smiling face with sunglasses",
    shortcut: null,
  },
  {
    emoji: "🥳",
    name: "派对脸",
    category: "笑脸和情感/笑脸",
    description: "partying face",
    shortcut: null,
  },
  {
    emoji: "🤩",
    name: "星星眼",
    category: "笑脸和情感/笑脸",
    description: "star-struck",
    shortcut: null,
  },
  {
    emoji: "🥺",
    name: "求你了",
    category: "笑脸和情感/笑脸",
    description: "pleading face",
    shortcut: null,
  },
  {
    emoji: "😋",
    name: "好吃",
    category: "笑脸和情感/笑脸",
    description: "face savoring food",
    shortcut: null,
  },
  {
    emoji: "😌",
    name: "松了一口气",
    category: "笑脸和情感/笑脸",
    description: "relieved face",
    shortcut: null,
  },
  {
    emoji: "🤭",
    name: "捂嘴笑",
    category: "笑脸和情感/笑脸",
    description: "face with hand over mouth",
    shortcut: null,
  },
  {
    emoji: "🧐",
    name: "单片眼镜",
    category: "笑脸和情感/笑脸",
    description: "face with monocle",
    shortcut: null,
  },
  {
    emoji: "🤨",
    name: "挑眉",
    category: "笑脸和情感/笑脸",
    description: "face with raised eyebrow",
    shortcut: null,
  },
  {
    emoji: "🥴",
    name: "晕头转向",
    category: "笑脸和情感/笑脸",
    description: "woozy face",
    shortcut: null,
  },
  {
    emoji: "🤤",
    name: "流口水",
    category: "笑脸和情感/笑脸",
    description: "drooling face",
    shortcut: null,
  },
  {
    emoji: "😪",
    name: "困",
    category: "笑脸和情感/笑脸",
    description: "sleepy face",
    shortcut: null,
  },
  {
    emoji: "🥵",
    name: "热",
    category: "笑脸和情感/笑脸",
    description: "hot face",
    shortcut: null,
  },
  {
    emoji: "🥶",
    name: "冷",
    category: "笑脸和情感/笑脸",
    description: "cold face",
    shortcut: null,
  },
  {
    emoji: "🥸",
    name: "伪装",
    category: "笑脸和情感/笑脸",
    description: "disguised face",
    shortcut: null,
  },
  {
    emoji: "😵",
    name: "晕",
    category: "笑脸和情感/笑脸",
    description: "dizzy face",
    shortcut: null,
  },
  {
    emoji: "🤕",
    name: "受伤的头",
    category: "笑脸和情感/笑脸",
    description: "face with head-bandage",
    shortcut: null,
  },
  {
    emoji: "😳",
    name: "脸红",
    category: "笑脸和情感/笑脸",
    description: "flushed face",
    shortcut: null,
  },
  {
    emoji: "😰",
    name: "焦虑",
    category: "笑脸和情感/笑脸",
    description: "anxious face with sweat",
    shortcut: null,
  },
  {
    emoji: "🤬",
    name: "咒骂",
    category: "笑脸和情感/笑脸",
    description: "face with symbols on mouth",
    shortcut: null,
  },
  {
    emoji: "😡",
    name: "愤怒",
    category: "笑脸和情感/笑脸",
    description: "pouting face",
    shortcut: null,
  },
  {
    emoji: "👿",
    name: "恶魔",
    category: "笑脸和情感/笑脸",
    description: "angry face with horns",
    shortcut: null,
  },
  {
    emoji: "🥹",
    name: "感动",
    category: "笑脸和情感/笑脸",
    description: "face holding back tears",
    shortcut: null,
  },
  {
    emoji: "🫠",
    name: "融化脸",
    category: "笑脸和情感/笑脸",
    description: "melting face",
    shortcut: null,
  },
  {
    emoji: "🫢",
    name: "偷看",
    category: "笑脸和情感/笑脸",
    description: "face with open eyes and hand over mouth",
    shortcut: null,
  },
  {
    emoji: "🫣",
    name: "眯眼偷看",
    category: "笑脸和情感/笑脸",
    description: "face with peeking eye",
    shortcut: null,
  },
  {
    emoji: "🫤",
    name: "斜嘴",
    category: "笑脸和情感/笑脸",
    description: "face with diagonal mouth",
    shortcut: null,
  },
  {
    emoji: "🥹",
    name: "含泪微笑",
    category: "笑脸和情感/笑脸",
    description: "face holding back tears",
    shortcut: null,
  },
  {
    emoji: "🫥",
    name: "虚线脸",
    category: "笑脸和情感/笑脸",
    description: "dotted line face",
    shortcut: null,
  },

  // 笑脸和情感/表情脸
  {
    emoji: "😍",
    name: "花痴",
    category: "笑脸和情感/表情脸",
    description: "smiling face with heart-eyes",
    shortcut: "Alt+2",
  },
  {
    emoji: "👻",
    name: "鬼魂",
    category: "笑脸和情感/表情脸",
    description: "ghost",
    shortcut: null,
  },
  {
    emoji: "💩",
    name: "便便",
    category: "笑脸和情感/表情脸",
    description: "pile of poo",
    shortcut: null,
  },
  {
    emoji: "💀",
    name: "骷髅",
    category: "笑脸和情感/表情脸",
    description: "skull",
    shortcut: null,
  },

  // ====================
  // 人物类
  // ====================
  
  // 人物/手势
  {
    emoji: "👍",
    name: "赞",
    category: "人物/手势",
    description: "thumbs up",
    shortcut: null,
  },
  {
    emoji: "👎",
    name: "踩",
    category: "人物/手势",
    description: "thumbs down",
    shortcut: null,
  },
  {
    emoji: "👌",
    name: "OK手势",
    category: "人物/手势",
    description: "OK hand",
    shortcut: null,
  },
  {
    emoji: "🤝",
    name: "握手",
    category: "人物/手势",
    description: "handshake",
    shortcut: null,
  },
  {
    emoji: "✌️",
    name: "胜利",
    category: "人物/手势",
    description: "victory hand",
    shortcut: null,
  },
  
  // 人物/职业
  {
    emoji: "👨‍⚕️",
    name: "男医生",
    category: "人物/职业",
    description: "man health worker",
    shortcut: null,
  },
  {
    emoji: "👩‍⚕️",
    name: "女医生",
    category: "人物/职业",
    description: "woman health worker",
    shortcut: null,
  },
  {
    emoji: "👨‍🏫",
    name: "男老师",
    category: "人物/职业",
    description: "man teacher",
    shortcut: null,
  },
  {
    emoji: "👩‍🏫",
    name: "女老师",
    category: "人物/职业",
    description: "woman teacher",
    shortcut: null,
  },
  
  // ====================
  // 动物与自然类
  // ====================
  
  // 动物与自然/动物哺乳类
  {
    emoji: "🐶",
    name: "狗",
    category: "动物与自然/动物哺乳类",
    description: "dog face",
    shortcut: null,
  },
  {
    emoji: "🐱",
    name: "猫",
    category: "动物与自然/动物哺乳类",
    description: "cat face",
    shortcut: null,
  },
  {
    emoji: "🐭",
    name: "老鼠",
    category: "动物与自然/动物哺乳类",
    description: "mouse face",
    shortcut: null,
  },
  {
    emoji: "🐹",
    name: "仓鼠",
    category: "动物与自然/动物哺乳类",
    description: "hamster face",
    shortcut: null,
  },
  {
    emoji: "🐰",
    name: "兔子",
    category: "动物与自然/动物哺乳类",
    description: "rabbit face",
    shortcut: null,
  },
  {
    emoji: "🦊",
    name: "狐狸",
    category: "动物与自然/动物哺乳类",
    description: "fox face",
    shortcut: null,
  },
  {
    emoji: "🐻",
    name: "熊",
    category: "动物与自然/动物哺乳类",
    description: "bear face",
    shortcut: null,
  },
  {
    emoji: "🐼",
    name: "熊猫",
    category: "动物与自然/动物哺乳类",
    description: "panda face",
    shortcut: null,
  },
  {
    emoji: "🦁",
    name: "狮子",
    category: "动物与自然/动物哺乳类",
    description: "lion face",
    shortcut: null,
  },
  {
    emoji: "🐯",
    name: "老虎",
    category: "动物与自然/动物哺乳类",
    description: "tiger face",
    shortcut: null,
  },
  {
    emoji: "🦓",
    name: "斑马",
    category: "动物与自然/动物哺乳类",
    description: "zebra",
    shortcut: null,
  },
  {
    emoji: "🦒",
    name: "长颈鹿",
    category: "动物与自然/动物哺乳类",
    description: "giraffe",
    shortcut: null,
  },
  {
    emoji: "🦬",
    name: "野牛",
    category: "动物与自然/动物哺乳类",
    description: "bison",
    shortcut: null,
  },
  {
    emoji: "🦣",
    name: "猛犸象",
    category: "动物与自然/动物哺乳类",
    description: "mammoth",
    shortcut: null,
  },
  {
    emoji: "🐘",
    name: "大象",
    category: "动物与自然/动物哺乳类",
    description: "elephant",
    shortcut: null,
  },
  {
    emoji: "🦏",
    name: "犀牛",
    category: "动物与自然/动物哺乳类",
    description: "rhinoceros",
    shortcut: null,
  },
  {
    emoji: "🦛",
    name: "河马",
    category: "动物与自然/动物哺乳类",
    description: "hippopotamus",
    shortcut: null,
  },

  // 动物与自然/动物鸟类
  {
    emoji: "🦅",
    name: "鹰",
    category: "动物与自然/动物鸟类",
    description: "eagle",
    shortcut: null,
  },
  {
    emoji: "🦆",
    name: "鸭子",
    category: "动物与自然/动物鸟类",
    description: "duck",
    shortcut: null,
  },
  {
    emoji: "🦉",
    name: "猫头鹰",
    category: "动物与自然/动物鸟类",
    description: "owl",
    shortcut: null,
  },
  {
    emoji: "🦜",
    name: "鹦鹉",
    category: "动物与自然/动物鸟类",
    description: "parrot",
    shortcut: null,
  },
  {
    emoji: "🦢",
    name: "天鹅",
    category: "动物与自然/动物鸟类",
    description: "swan",
    shortcut: null,
  },
  {
    emoji: "🦩",
    name: "火烈鸟",
    category: "动物与自然/动物鸟类",
    description: "flamingo",
    shortcut: null,
  },
  {
    emoji: "🐓",
    name: "公鸡",
    category: "动物与自然/动物鸟类",
    description: "rooster",
    shortcut: null,
  },
  {
    emoji: "🦃",
    name: "火鸡",
    category: "动物与自然/动物鸟类",
    description: "turkey",
    shortcut: null,
  },
  {
    emoji: "🦚",
    name: "孔雀",
    category: "动物与自然/动物鸟类",
    description: "peacock",
    shortcut: null,
  },

  // 动物与自然/爬行动物
  {
    emoji: "🐊",
    name: "鳄鱼",
    category: "动物与自然/爬行动物",
    description: "crocodile",
    shortcut: null,
  },
  {
    emoji: "🐢",
    name: "乌龟",
    category: "动物与自然/爬行动物",
    description: "turtle",
    shortcut: null,
  },
  {
    emoji: "🦎",
    name: "蜥蜴",
    category: "动物与自然/爬行动物",
    description: "lizard",
    shortcut: null,
  },
  {
    emoji: "🐍",
    name: "蛇",
    category: "动物与自然/爬行动物",
    description: "snake",
    shortcut: null,
  },
  {
    emoji: "🐲",
    name: "龙",
    category: "动物与自然/爬行动物",
    description: "dragon face",
    shortcut: null,
  },

  // 动物与自然/动物海洋
  {
    emoji: "🐙",
    name: "章鱼",
    category: "动物与自然/动物海洋",
    description: "octopus",
    shortcut: null,
  },
  {
    emoji: "🦑",
    name: "鱿鱼",
    category: "动物与自然/动物海洋",
    description: "squid",
    shortcut: null,
  },
  {
    emoji: "🦐",
    name: "虾",
    category: "动物与自然/动物海洋",
    description: "shrimp",
    shortcut: null,
  },
  {
    emoji: "🐬",
    name: "海豚",
    category: "动物与自然/动物海洋",
    description: "dolphin",
    shortcut: null,
  },
  {
    emoji: "🐋",
    name: "鲸鱼",
    category: "动物与自然/动物海洋",
    description: "whale",
    shortcut: null,
  },
  {
    emoji: "🦈",
    name: "鲨鱼",
    category: "动物与自然/动物海洋",
    description: "shark",
    shortcut: null,
  },
  {
    emoji: "🐠",
    name: "热带鱼",
    category: "动物与自然/动物海洋",
    description: "tropical fish",
    shortcut: null,
  },
  {
    emoji: "🐡",
    name: "河豚",
    category: "动物与自然/动物海洋",
    description: "blowfish",
    shortcut: null,
  },
  {
    emoji: "🦞",
    name: "龙虾",
    category: "动物与自然/动物海洋",
    description: "lobster",
    shortcut: null,
  },
  {
    emoji: "🦀",
    name: "螃蟹",
    category: "动物与自然/动物海洋",
    description: "crab",
    shortcut: null,
  },
  {
    emoji: "🐚",
    name: "海螺",
    category: "动物与自然/动物海洋",
    description: "spiral shell",
    shortcut: null,
  },
  {
    emoji: "🪼",
    name: "水母",
    category: "动物与自然/动物海洋",
    description: "jellyfish",
    shortcut: null,
  },
  {
    emoji: "🐳",
    name: "喷水鲸鱼",
    category: "动物与自然/动物海洋",
    description: "spouting whale",
    shortcut: null,
  },

  // 动物与自然/昆虫
  {
    emoji: "🐝",
    name: "蜜蜂",
    category: "动物与自然/昆虫",
    description: "honeybee",
    shortcut: null,
  },
  {
    emoji: "🪱",
    name: "蠕虫",
    category: "动物与自然/昆虫",
    description: "worm",
    shortcut: null,
  },
  {
    emoji: "🦋",
    name: "蝴蝶",
    category: "动物与自然/昆虫",
    description: "butterfly",
    shortcut: null,
  },
  {
    emoji: "🐛",
    name: "毛毛虫",
    category: "动物与自然/昆虫",
    description: "bug",
    shortcut: null,
  },
  {
    emoji: "🐌",
    name: "蜗牛",
    category: "动物与自然/昆虫",
    description: "snail",
    shortcut: null,
  },
  {
    emoji: "🦗",
    name: "蟋蟀",
    category: "动物与自然/昆虫",
    description: "cricket",
    shortcut: null,
  },
  {
    emoji: "🐜",
    name: "蚂蚁",
    category: "动物与自然/昆虫",
    description: "ant",
    shortcut: null,
  },
  {
    emoji: "🕷️",
    name: "蜘蛛",
    category: "动物与自然/昆虫",
    description: "spider",
    shortcut: null,
  },
  {
    emoji: "🦂",
    name: "蝎子",
    category: "动物与自然/昆虫",
    description: "scorpion",
    shortcut: null,
  },

  // 动物与自然/植物
  {
    emoji: "🌸",
    name: "樱花",
    category: "动物与自然/植物",
    description: "cherry blossom",
    shortcut: null,
  },
  {
    emoji: "🌹",
    name: "玫瑰",
    category: "动物与自然/植物",
    description: "rose",
    shortcut: null,
  },
  {
    emoji: "🌻",
    name: "向日葵",
    category: "动物与自然/植物",
    description: "sunflower",
    shortcut: null,
  },
  {
    emoji: "🌲",
    name: "常青树",
    category: "动物与自然/植物",
    description: "evergreen tree",
    shortcut: null,
  },
  {
    emoji: "🌵",
    name: "仙人掌",
    category: "动物与自然/植物",
    description: "cactus",
    shortcut: null,
  },
  {
    emoji: "🌷",
    name: "郁金香",
    category: "动物与自然/植物",
    description: "tulip",
    shortcut: null,
  },
  {
    emoji: "🌺",
    name: "芙蓉花",
    category: "动物与自然/植物",
    description: "hibiscus",
    shortcut: null,
  },
  {
    emoji: "🪷",
    name: "荷花",
    category: "动物与自然/植物",
    description: "lotus",
    shortcut: null,
  },
  {
    emoji: "🪴",
    name: "盆栽",
    category: "动物与自然/植物",
    description: "potted plant",
    shortcut: null,
  },
  {
    emoji: "🪵",
    name: "木头",
    category: "动物与自然/植物",
    description: "wood",
    shortcut: null,
  },
  {
    emoji: "🍄",
    name: "蘑菇",
    category: "动物与自然/植物",
    description: "mushroom",
    shortcut: null,
  },
  {
    emoji: "🌱",
    name: "幼苗",
    category: "动物与自然/植物",
    description: "seedling",
    shortcut: null,
  },
  {
    emoji: "🌿",
    name: "草药",
    category: "动物与自然/植物",
    description: "herb",
    shortcut: null,
  },
  {
    emoji: "☘️",
    name: "三叶草",
    category: "动物与自然/植物",
    description: "shamrock",
    shortcut: null,
  },
  {
    emoji: "🍀",
    name: "四叶草",
    category: "动物与自然/植物",
    description: "four leaf clover",
    shortcut: null,
  },
  {
    emoji: "🍁",
    name: "枫叶",
    category: "动物与自然/植物",
    description: "maple leaf",
    shortcut: null,
  },
  {
    emoji: "🍂",
    name: "落叶",
    category: "动物与自然/植物",
    description: "fallen leaf",
    shortcut: null,
  },

  // 动物与自然/自然景观
  {
    emoji: "🏔️",
    name: "雪山",
    category: "动物与自然/自然景观",
    description: "snow-capped mountain",
    shortcut: null,
  },
  {
    emoji: "⛰️",
    name: "山",
    category: "动物与自然/自然景观",
    description: "mountain",
    shortcut: null,
  },
  {
    emoji: "🌋",
    name: "火山",
    category: "动物与自然/自然景观",
    description: "volcano",
    shortcut: null,
  },
  {
    emoji: "🏝️",
    name: "荒岛",
    category: "动物与自然/自然景观",
    description: "desert island",
    shortcut: null,
  },
  {
    emoji: "🏜️",
    name: "沙漠",
    category: "动物与自然/自然景观",
    description: "desert",
    shortcut: null,
  },

  // 天气/自然现象
  {
    emoji: "🌞",
    name: "太阳",
    category: "天气/自然现象",
    description: "sun with face",
    shortcut: null,
  },
  {
    emoji: "🌛",
    name: "月亮",
    category: "天气/自然现象",
    description: "first quarter moon face",
    shortcut: null,
  },
  {
    emoji: "🌈",
    name: "彩虹",
    category: "天气/自然现象",
    description: "rainbow",
    shortcut: null,
  },
  {
    emoji: "⚡",
    name: "闪电",
    category: "天气/自然现象",
    description: "high voltage",
    shortcut: null,
  },
  {
    emoji: "❄️",
    name: "雪花",
    category: "天气/自然现象",
    description: "snowflake",
    shortcut: null,
  },

  // ====================
  // 食物与饮料类
  // ====================
  
  // 食物与饮料/水果
  {
    emoji: "🍎",
    name: "红苹果",
    category: "食物与饮料/水果",
    description: "red apple",
    shortcut: null,
  },
  {
    emoji: "🍊",
    name: "橘子",
    category: "食物与饮料/水果",
    description: "tangerine",
    shortcut: null,
  },
  {
    emoji: "🍌",
    name: "香蕉",
    category: "食物与饮料/水果",
    description: "banana",
    shortcut: null,
  },
  {
    emoji: "🍉",
    name: "西瓜",
    category: "食物与饮料/水果",
    description: "watermelon",
    shortcut: null,
  },
  {
    emoji: "🍓",
    name: "草莓",
    category: "食物与饮料/水果",
    description: "strawberry",
    shortcut: null,
  },
  {
    emoji: "🍍",
    name: "菠萝",
    category: "食物与饮料/水果",
    description: "pineapple",
    shortcut: null,
  },

  // ====================
  // 符号类
  // ====================
  
  // 符号/箭头
  {
    emoji: "⬆️",
    name: "上箭头",
    category: "符号/箭头",
    description: "up arrow",
    shortcut: null,
  },
  {
    emoji: "⬇️",
    name: "下箭头",
    category: "符号/箭头",
    description: "down arrow",
    shortcut: null,
  },
  {
    emoji: "➡️",
    name: "右箭头",
    category: "符号/箭头",
    description: "right arrow",
    shortcut: null,
  },
  {
    emoji: "⬅️",
    name: "左箭头",
    category: "符号/箭头",
    description: "left arrow",
    shortcut: null,
  },
  {
    emoji: "↩️",
    name: "左弯箭头",
    category: "符号/箭头",
    description: "right arrow curving left",
    shortcut: null,
  },
  {
    emoji: "↪️",
    name: "右弯箭头",
    category: "符号/箭头",
    description: "left arrow curving right",
    shortcut: null,
  },
  {
    emoji: "🔄",
    name: "循环箭头",
    category: "符号/箭头",
    description: "counterclockwise arrows button",
    shortcut: null,
  },
  {
    emoji: "🔃",
    name: "顺时针箭头",
    category: "符号/箭头",
    description: "clockwise vertical arrows",
    shortcut: null,
  },
  {
    emoji: "⤴️",
    name: "向上弯箭头",
    category: "符号/箭头",
    description: "right arrow curving up",
    shortcut: null,
  },
  {
    emoji: "⤵️",
    name: "向下弯箭头",
    category: "符号/箭头",
    description: "right arrow curving down",
    shortcut: null,
  },
  {
    emoji: "🔙",
    name: "返回箭头",
    category: "符号/箭头",
    description: "BACK arrow",
    shortcut: null,
  },
  {
    emoji: "🔚",
    name: "结束箭头",
    category: "符号/箭头",
    description: "END arrow",
    shortcut: null,
  },
  {
    emoji: "🔛",
    name: "开启箭头",
    category: "符号/箭头",
    description: "ON! arrow",
    shortcut: null,
  },
  {
    emoji: "🔝",
    name: "顶部箭头",
    category: "符号/箭头",
    description: "TOP arrow",
    shortcut: null,
  },
  {
    emoji: "🔜",
    name: "即将到来箭头",
    category: "符号/箭头",
    description: "SOON arrow",
    shortcut: null,
  },
  {
    emoji: "⏫",
    name: "快速上箭头",
    category: "符号/箭头",
    description: "fast up button",
    shortcut: null,
  },
  {
    emoji: "⏬",
    name: "快速下箭头",
    category: "符号/箭头",
    description: "fast down button",
    shortcut: null,
  },

  // ====================
  // 物品类
  // ====================
  
  // 物品/工具
  {
    emoji: "🔧",
    name: "扳手",
    category: "物品/工具",
    description: "wrench",
    shortcut: null,
  },
  {
    emoji: "🔨",
    name: "锤子",
    category: "物品/工具",
    description: "hammer",
    shortcut: null,
  },
  {
    emoji: "⚒️",
    name: "锤子和镐",
    category: "物品/工具",
    description: "hammer and pick",
    shortcut: null,
  },
  {
    emoji: "🛠️",
    name: "锤子和扳手",
    category: "物品/工具",
    description: "hammer and wrench",
    shortcut: null,
  },
  {
    emoji: "⚏️",
    name: "镐",
    category: "物品/工具",
    description: "pick",
    shortcut: null,
  },
  {
    emoji: "🪓",
    name: "斧头",
    category: "物品/工具",
    description: "axe",
    shortcut: null,
  },
  {
    emoji: "🪚",
    name: "木工锯",
    category: "物品/工具",
    description: "carpentry saw",
    shortcut: null,
  },
  {
    emoji: "🔩",
    name: "螺母和螺栓",
    category: "物品/工具",
    description: "nut and bolt",
    shortcut: null,
  },
  {
    emoji: "⚙️",
    name: "齿轮",
    category: "物品/工具",
    description: "gear",
    shortcut: null,
  },
  {
    emoji: "🗜️",
    name: "夹钳",
    category: "物品/工具",
    description: "clamp",
    shortcut: null,
  },
  {
    emoji: "⚖️",
    name: "天平",
    category: "物品/工具",
    description: "balance scale",
    shortcut: null,
  },
  {
    emoji: "🧰",
    name: "工具箱",
    category: "物品/工具",
    description: "toolbox",
    shortcut: null,
  },
  {
    emoji: "🧲",
    name: "磁铁",
    category: "物品/工具",
    description: "magnet",
    shortcut: null,
  },
  {
    emoji: "🪜",
    name: "梯子",
    category: "物品/工具",
    description: "ladder",
    shortcut: null,
  },
  
  // 物品/办公用品
  {
    emoji: "✂️",
    name: "剪刀",
    category: "物品/办公用品",
    description: "scissors",
    shortcut: null,
  },
  {
    emoji: "📏",
    name: "直尺",
    category: "物品/办公用品",
    description: "straight ruler",
    shortcut: null,
  },
  {
    emoji: "📐",
    name: "三角尺",
    category: "物品/办公用品",
    description: "triangular ruler",
    shortcut: null,
  },
  {
    emoji: "📌",
    name: "图钉",
    category: "物品/办公用品",
    description: "pushpin",
    shortcut: null,
  },
  {
    emoji: "📍",
    name: "圆图钉",
    category: "物品/办公用品",
    description: "round pushpin",
    shortcut: null,
  },
  {
    emoji: "📎",
    name: "回形针",
    category: "物品/办公用品",
    description: "paperclip",
    shortcut: null,
  },
  {
    emoji: "🖇️",
    name: "链接回形针",
    category: "物品/办公用品",
    description: "linked paperclips",
    shortcut: null,
  },
  {
    emoji: "✏️",
    name: "铅笔",
    category: "物品/办公用品",
    description: "pencil",
    shortcut: null,
  },
  {
    emoji: "✒️",
    name: "黑色笔尖",
    category: "物品/办公用品",
    description: "black nib",
    shortcut: null,
  },
  {
    emoji: "🖋️",
    name: "钢笔",
    category: "物品/办公用品",
    description: "fountain pen",
    shortcut: null,
  },
  {
    emoji: "🖊️",
    name: "圆珠笔",
    category: "物品/办公用品",
    description: "pen",
    shortcut: null,
  },
  
  // 物品/家用电器
  {
    emoji: "🔌",
    name: "电源插头",
    category: "物品/家用电器",
    description: "electric plug",
    shortcut: null,
  },
  {
    emoji: "💡",
    name: "灯泡",
    category: "物品/家用电器",
    description: "light bulb",
    shortcut: null,
  },
  {
    emoji: "🔦",
    name: "手电筒",
    category: "物品/家用电器",
    description: "flashlight",
    shortcut: null,
  },
  {
    emoji: "🪫",
    name: "电量低",
    category: "物品/家用电器",
    description: "low battery",
    shortcut: null,
  },
  {
    emoji: "🔋",
    name: "电池",
    category: "物品/家用电器",
    description: "battery",
    shortcut: null,
  },
  {
    emoji: "🧯",
    name: "灭火器",
    category: "物品/工具",
    description: "fire extinguisher",
    shortcut: null,
  },

  // ====================
  // 科技类
  // ====================
  
  // 科技/实验室设备
  {
    emoji: "🧪",
    name: "试管",
    category: "科技/实验室设备",
    description: "test tube",
    shortcut: null,
  },
  {
    emoji: "⚗️",
    name: "蒸馏器",
    category: "科技/实验室设备",
    description: "alembic",
    shortcut: null,
  },
  {
    emoji: "🧫",
    name: "培养皿",
    category: "科技/实验室设备",
    description: "petri dish",
    shortcut: null,
  },
  {
    emoji: "🔬",
    name: "显微镜",
    category: "科技/实验室设备",
    description: "microscope",
    shortcut: null,
  },
  {
    emoji: "🔭",
    name: "望远镜",
    category: "科技/实验室设备",
    description: "telescope",
    shortcut: null,
  },
  {
    emoji: "🧬",
    name: "DNA",
    category: "科技/实验室设备",
    description: "dna",
    shortcut: null,
  },
  {
    emoji: "📡",
    name: "卫星天线",
    category: "科技/设备",
    description: "satellite antenna",
    shortcut: null,
  },
  
  // ====================
  // 医疗类
  // ====================
  
  // 医疗/器具
  {
    emoji: "💉",
    name: "注射器",
    category: "医疗/器具",
    description: "syringe",
    shortcut: null,
  },
  {
    emoji: "🩸",
    name: "血滴",
    category: "医疗/物品",
    description: "drop of blood",
    shortcut: null,
  },
  {
    emoji: "💊",
    name: "药丸",
    category: "医疗/物品",
    description: "pill",
    shortcut: null,
  },
  {
    emoji: "🩹",
    name: "创可贴",
    category: "医疗/物品",
    description: "adhesive bandage",
    shortcut: null,
  },
  {
    emoji: "🩼",
    name: "拐杖",
    category: "医疗/器具",
    description: "crutch",
    shortcut: null,
  },
  {
    emoji: "🩺",
    name: "听诊器",
    category: "医疗/器具",
    description: "stethoscope",
    shortcut: null,
  },
  {
    emoji: "🦴",
    name: "骨头",
    category: "医疗/物品",
    description: "bone",
    shortcut: null,
  },
  {
    emoji: "🦷",
    name: "牙齿",
    category: "医疗/物品",
    description: "tooth",
    shortcut: null,
  },
  {
    emoji: "🩻",
    name: "X射线",
    category: "医疗/器具",
    description: "x-ray",
    shortcut: null,
  },
  {
    emoji: "🧠",
    name: "大脑",
    category: "医疗/器官",
    description: "brain",
    shortcut: null,
  },
  {
    emoji: "🫀",
    name: "心脏",
    category: "医疗/器官",
    description: "anatomical heart",
    shortcut: null,
  },
  {
    emoji: "🫁",
    name: "肺",
    category: "医疗/器官",
    description: "lungs",
    shortcut: null,
  },

  // ====================
  // 家居类
  // ====================
  
  // 家居/基础设施
  {
    emoji: "🚪",
    name: "门",
    category: "家居/基础设施",
    description: "door",
    shortcut: null,
  },
  {
    emoji: "🪟",
    name: "窗户",
    category: "家居/基础设施",
    description: "window",
    shortcut: null,
  },
  {
    emoji: "🛗",
    name: "电梯",
    category: "家居/基础设施",
    description: "elevator",
    shortcut: null,
  },
  {
    emoji: "🪞",
    name: "镜子",
    category: "家居/基础设施",
    description: "mirror",
    shortcut: null,
  },
  
  // 家居/家具
  {
    emoji: "🛏️",
    name: "床",
    category: "家居/家具",
    description: "bed",
    shortcut: null,
  },
  {
    emoji: "🪑",
    name: "椅子",
    category: "家居/家具",
    description: "chair",
    shortcut: null,
  },
  {
    emoji: "🚽",
    name: "马桶",
    category: "家居/卫浴",
    description: "toilet",
    shortcut: null,
  },
  {
    emoji: "🛁",
    name: "浴缸",
    category: "家居/卫浴",
    description: "bathtub",
    shortcut: null,
  },
  {
    emoji: "🚿",
    name: "淋浴",
    category: "家居/卫浴",
    description: "shower",
    shortcut: null,
  },
  {
    emoji: "🧹",
    name: "扫帚",
    category: "家居/清洁用品",
    description: "broom",
    shortcut: null,
  },
  {
    emoji: "🧺",
    name: "篮",
    category: "家居/家具",
    description: "basket",
    shortcut: null,
  },
  {
    emoji: "🧴",
    name: "乳液瓶",
    category: "家居/卫浴",
    description: "lotion bottle",
    shortcut: null,
  },
  {
    emoji: "🧻",
    name: "卷纸",
    category: "家居/卫浴",
    description: "roll of paper",
    shortcut: null,
  },
  {
    emoji: "🪣",
    name: "桶",
    category: "家居/清洁用品",
    description: "bucket",
    shortcut: null,
  },
  {
    emoji: "🧽",
    name: "海绵",
    category: "家居/清洁用品",
    description: "sponge",
    shortcut: null,
  },
  {
    emoji: "🧼",
    name: "肥皂",
    category: "家居/卫浴",
    description: "soap",
    shortcut: null,
  },
  {
    emoji: "🪒",
    name: "剃须刀",
    category: "家居/卫浴",
    description: "razor",
    shortcut: null,
  },
  {
    emoji: "🪥",
    name: "牙刷",
    category: "家居/卫浴",
    description: "toothbrush",
    shortcut: null,
  },
  {
    emoji: "🪦",
    name: "墓碑",
    category: "家居/装饰",
    description: "headstone",
    shortcut: null,
  },
  {
    emoji: "🧸",
    name: "泰迪熊",
    category: "家居/装饰",
    description: "teddy bear",
    shortcut: null,
  },
  {
    emoji: "🪆",
    name: "套娃",
    category: "家居/装饰",
    description: "nesting dolls",
    shortcut: null,
  },
  {
    emoji: "🛒",
    name: "购物车",
    category: "家居/购物",
    description: "shopping cart",
    shortcut: null,
  },
  {
    emoji: "🔥",
    name: "火焰",
    category: "家居/元素",
    description: "fire",
    shortcut: null,
  },
  {
    emoji: "🧨",
    name: "鞭炮",
    category: "家居/装饰",
    description: "firecracker",
    shortcut: null,
  },
  {
    emoji: "🎈",
    name: "气球",
    category: "家居/装饰",
    description: "balloon",
    shortcut: null,
  },
  {
    emoji: "🎭",
    name: "表演艺术",
    category: "家居/装饰",
    description: "performing arts",
    shortcut: null,
  },
  {
    emoji: "🧩",
    name: "拼图",
    category: "家居/娱乐",
    description: "puzzle piece",
    shortcut: null,
  },
  {
    emoji: "🧶",
    name: "纱线",
    category: "家居/手工",
    description: "yarn",
    shortcut: null,
  },
  {
    emoji: "🔍",
    name: "放大镜",
    category: "家居/工具",
    description: "magnifying glass",
    shortcut: null,
  },
  {
    emoji: "📿",
    name: "念珠",
    category: "家居/装饰",
    description: "prayer beads",
    shortcut: null,
  },
];

module.exports = emojiData;
